### PR TITLE
feat: add HTML minifier (resolves #20)

### LINKED ISSUE #20: Add HTML minify transform
## Is your feature request related to a problem?

We include a default transform in many of our projects which minifies the generated HTML.
## Describe the solution you'd like

This transform should be included in the plugin.

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

Not applicable.

### PR DESCRIPTION
**Pull request by greatislander**
This PR adds an Eleventy transform which will minify generated HTML.

### CODE REVIEW

**Review by BlueSlug — COMMENTED** [review]
UIO doesn't seem to be loading properly, not sure what the issue is:

2021-01-15 Trivet minify UIO bug

**Comment by greatislander** [comment]
@BlueSlug If you run `npm start` from within the `eleventy-plugin-fluid` directory, what happens? You should get a locally-served minimal site with working UIO and minified HTML output.

**Comment by greatislander** [comment]
(I assume based on the screenshot you are testing this branch within Trivet— not sure what's happening there.)

**Review by BlueSlug — APPROVED** [review]
Sorry it's taken so long for me to get back to this PR, @greatislander!

The build works fine, the HTML was minified, and I did not note any errors.

**Pull request merged**
