### PR TITLE
feat: add passthroughCopy and shortcodes for UIO (resolves #2)

### LINKED ISSUE #2: Add UIO shortcodes and passthrough copy configuration

### PR DESCRIPTION
**Pull request by greatislander**
- [x] Adds passthrough file copy configuration for UIO components.
- [x] Adds shortcodes for loading UIO dependencies into base templates and initializing UIO.

See docs for [shortcodes](https://github.com/fluid-project/eleventy-plugin-fluid/blob/041e4802197fdbcdf36086d8f5fa26821a48957a/README.md#shortcodes) and [passthrough copy](https://github.com/fluid-project/eleventy-plugin-fluid/blob/041e4802197fdbcdf36086d8f5fa26821a48957a/README.md#passthrough-copy).

### CODE REVIEW

**Comment by jhung** [comment]
@greatislander I can imagine situations where the integrator may be using a different version of Infusion which may use different markup.

Is there a way to programatically generate this shortcode based on the version of infusion being used? If not, then it may be worth documenting somewhere the markup in `src/shortcodes/uio.js` may need changing if using different Infusion versions. Maybe @jobara may have some thoughts.

**Comment by jobara** [comment]
It would be good to test that UIO is actually working with the supplied configuration. Are we assuming that UIO and Infusion are only being updated through this plugin? 

Another thing we should consider is that different sites might want a different setup for UIO. For example, the WeCount site doesn't use the text-size option.

**Comment by greatislander** [comment]
@jhung @jobara This plugin bundles the latest release of Infusion/UIO and provides a working, default UIO configuration. If an integrator wants to use a custom build or a different version, it probably makes sense for them to ignore these shortcodes.

One complexity with using a different version is that this plugin handles all of the complex passthrough copy configuration for the included version of UIO; it would probably make sense to allow an integrator to disable that configuration so that they can use their own. My intention, however, was that this plugin would track any changes in the Infusion package (e.g. [FLUID-6359](https://issues.fluidproject.org/browse/FLUID-6359)) and make sure that all the necessary files would be copied and loaded into the page head.

**Comment by jobara** [comment]
@greatislander regarding my second point about different UIO configurations is that different sites might have different options passed into the UIO's initialization function. When `uioInit` is called in the template, can it take arguments? If so we should pass those along to the initialization function.

**Comment by greatislander** [comment]
@jobara Yes, the shortcode could take arguments. What arguments would be needed to allow the desired level of customization?

**Comment by greatislander** [comment]
See examples here: https://www.11ty.dev/docs/shortcodes/#shortcodes

**Comment by jobara** [comment]
> @jobara Yes, the shortcode could take arguments. What arguments would be needed to allow the desired level of customization?

You should just provide access to all of the parameters to `fluid.uiOptions.prefsEditor`: `container` and `options`. You can use what you have there already as the default values. For the options you'll need to decide if want to merge the options or override. I think you probably want the former so it might be simplest to setup a new grade/component.

**Comment by greatislander** [comment]
@jhung @jobara I'd like to propose that rather than trying to send pass JSON configuration to a shortcode, we leave this functionality as is (providing the default integration of UIO) and leave developers with instructions on how to add a custom integration in place of that supplied by the shortcodes. Thoughts? I've updated the documentation accordingly: https://github.com/fluid-project/eleventy-plugin-fluid/blob/f9606f4ee6b2880dae63eded18bd894c54588863/README.md

**Comment by jobara** [comment]
> @jhung @jobara I'd like to propose that rather than trying to send pass JSON configuration to a shortcode, we leave this functionality as is (providing the default integration of UIO) and leave developers with instructions on how to add a custom integration in place of that supplied by the shortcodes. Thoughts? I've updated the documentation accordingly: https://github.com/fluid-project/eleventy-plugin-fluid/blob/f9606f4ee6b2880dae63eded18bd894c54588863/README.md

@greatislander I believe that's what we agreed on in a conversation a while back now. I'll @jhung confirm. Regarding the docs it isn't entirely clear to me what needs to go where in the base.njk file. I don't see where `{% uioInit %}` is used there.

**Comment by greatislander** [comment]
> Regarding the docs it isn't entirely clear to me what needs to go where in the base.njk file. I don't see where `{% uioInit %}` is used there.

@jobara The reason it's not there is that this PR isn't merged and fluidic-11ty doesn't have access to these shortcodes. Once the shortcodes are available the base file will be much more helpful (and I'll probably link to a specific line at a history point to make it abundantly clear).

**Review by jhung — APPROVED** [review]

**Pull request merged**
